/* ==========================================================================
   scenes.js —— 拍摄场景 / 摄影手法 / 光位 / 构图
   ev    : 环境亮度 EV100（决定测光基准）
   dist  : 默认拍摄距离（米），参与景深计算
   speed : 主体运动速度（米/秒），参与运动模糊计算
   ========================================================================== */
window.SCENES = [
  /* ---------------- 人像 ---------------- */
  { id: 'studio-portrait', cn: '影棚人像', cat: '人像', ev: 10, dist: 2.5, speed: 0,
    prompt: 'studio portrait of a young woman with expressive eyes and natural makeup, seated against a seamless mid-grey backdrop, calm confident gaze straight into the lens, visible skin texture and fine facial detail',
    note: '布光教学的主场。手动控制光位，观察鼻影、颧骨阴影与眼神光的变化。' },
  { id: 'street-portrait', cn: '街头人像', cat: '人像', ev: 12, dist: 3, speed: 0,
    prompt: 'environmental street portrait of a man in a worn leather jacket leaning against a weathered brick wall, candid natural expression, late afternoon light raking across his face, shallow depth separating him from a busy street',
    note: '环境人像：人物 + 环境都要说话。用 35mm 交代场景，用 85mm 突出人物。' },
  { id: 'wedding', cn: '婚礼', cat: '人像', ev: 11, dist: 4, speed: 0.4,
    prompt: 'wedding photograph of a bride and groom in a sunlit garden, the bride laughing mid-turn in her white lace dress, backlit rim light through the veil, dreamy romantic atmosphere',
    note: '高反差场景。白纱是最容易过曝的地方——看测光表怎么被它骗。' },
  { id: 'child', cn: '儿童', cat: '人像', ev: 12, dist: 2, speed: 2.2,
    prompt: 'candid photograph of a small child running through tall grass laughing, arms outstretched, sunlit dust motes in the air, unposed joyful energy',
    note: '孩子不会等你的快门。1/500 以上是底线。' },
  { id: 'dancer', cn: '舞者', cat: '人像', ev: 9, dist: 5, speed: 3.5,
    prompt: 'photograph of a contemporary dancer mid-leap on a dark stage, body arched in a sculptural pose, dramatic single spotlight from above, dust and chalk powder suspended in the light beam',
    note: '运动与光的结合。凝固一次腾空，还是拖出舞蹈的轨迹？' },
  { id: 'elder', cn: '老人肖像', cat: '人像', ev: 9, dist: 1.8, speed: 0,
    prompt: 'intimate portrait of an elderly craftsman with deeply lined hands and weathered face, looking down at his work, soft window light from the side, every wrinkle and pore rendered with dignity',
    note: '伦勃朗布光的经典对象。侧光把皱纹变成故事。' },

  /* ---------------- 风光 ---------------- */
  { id: 'mountain-sunrise', cn: '山峦日出', cat: '风光', ev: 10, dist: 1000, speed: 0.02,
    prompt: 'wide landscape of jagged snow-capped mountain peaks at sunrise, valley filled with a sea of low clouds, first pink-orange light striking the summits, sky in soft gradient from amber to deep blue',
    note: '大景深 + 渐变灰。对焦点放哪里决定了前景还是远山清晰。' },
  { id: 'seaside', cn: '海岸礁石', cat: '风光', ev: 9, dist: 30, speed: 4,
    prompt: 'rocky coastline with black volcanic boulders at sunset, waves washing over dark wet rocks, dramatic orange and purple sky, sea spray suspended in the air',
    note: '长曝的圣地。30 秒把海浪变成丝绸，4 秒保住它的力量。' },
  { id: 'waterfall', cn: '瀑布', cat: '风光', ev: 8, dist: 15, speed: 3,
    prompt: 'a tall waterfall cascading over moss-covered basalt cliffs deep in a green gorge, water crashing into a turquoise pool below, fine mist filling the air, ferns clinging to the rock walls',
    note: '快门速度决定水的性格：1/1000 是冰凌，1 秒是绸缎。' },
  { id: 'misty-forest', cn: '迷雾森林', cat: '风光', ev: 8, dist: 20, speed: 0.1,
    prompt: 'a forest path disappearing into thick morning fog between immense mossy tree trunks, shafts of pale light cutting through the mist, dew on spiderwebs, deep quiet atmosphere',
    note: '雾会压缩层次。逆光下的雾是天然的柔光箱。' },
  { id: 'desert', cn: '沙漠沙丘', cat: '风光', ev: 14, dist: 200, speed: 1,
    prompt: 'abstract sand dunes in late afternoon, one sharp sinuous ridge curving across the frame, wind-blown sand streaming off the crest, razor-sharp light-shadow boundary, minimalist composition',
    note: '沙丘是「线条与形状」最好的教材。低角度侧光才能立起沙脊。' },
  { id: 'snowfield', cn: '雪原', cat: '风光', ev: 16, dist: 80, speed: 0.5,
    prompt: 'a lone figure walking across an endless snowfield under a brilliant blue sky, footprint trail leading into the distance, blinding white expanse with deep blue shadows in the drifts',
    note: '雪会骗你的测光表——它想让雪变灰。EV 16，注意补偿。' },

  /* ---------------- 夜景 ---------------- */
  { id: 'neon-night', cn: '雨夜霓虹', cat: '夜景', ev: 5, dist: 6, speed: 1.3,
    prompt: 'rain-soaked city street at night, walls of glowing neon signs in Japanese and Chinese reflecting in the wet asphalt, pedestrians with umbrellas silhouetted against the light, steam rising from a vent',
    note: 'CineStill 800T 的主场。看高光周围的红色光晕。' },
  { id: 'starscape', cn: '星空银河', cat: '夜景', ev: -4, dist: 100, speed: 0.001,
    prompt: 'the Milky Way arching across a pitch-black desert night sky, thousands of stars, silhouetted rock formations in the foreground, faint airglow on the horizon',
    note: '500 法则：焦距 × 秒数 ≤ 500，星星才不会拖线。' },
  { id: 'light-trails', cn: '车流光轨', cat: '夜景', ev: 6, dist: 40, speed: 16,
    prompt: 'a city overpass at night from above, headlights and taillights streaming into long continuous ribbons of red and white light, static city skyline sharp behind the light trails',
    note: '长曝的入门课。车流是画笔，快门时间是笔画的长度。' },
  { id: 'fairground', cn: '游乐园夜拍', cat: '夜景', ev: 6, dist: 25, speed: 8,
    prompt: 'a ferris wheel and carousel spinning at night, their lights blurred into concentric circles of colour, a child watching in silhouette, candy-coloured glow on the fairground floor',
    note: '旋转的灯变成圆环——这是快门速度的可视化。' },
  { id: 'concert', cn: '演出现场', cat: '夜景', ev: 6, dist: 12, speed: 2.5,
    prompt: 'a rock band performing on stage, singer leaning into the microphone drenched in sweat, hard backlit spotlights cutting through haze, silhouetted audience with raised hands in the foreground',
    note: '高 ISO 的战场。3200 的颗粒在这里是质感不是缺陷。' },

  /* ---------------- 建筑 ---------------- */
  { id: 'architecture', cn: '建筑几何', cat: '建筑', ev: 12, dist: 60, speed: 0,
    prompt: 'a brutalist concrete building photographed against a clear sky, strong repeating geometric grid of windows, converging vertical lines, harsh midday shadow dividing the facade into light and dark planes',
    note: '移轴镜头的意义：让垂直线真的垂直。' },
  { id: 'interior', cn: '室内空间', cat: '建筑', ev: 7, dist: 8, speed: 0,
    prompt: 'the interior of a minimalist modern house, floor-to-ceiling windows pouring daylight across a polished concrete floor, a single chair and a long shadow, calm architectural composition',
    note: '室内是宽容度考试：窗外的天空和室内的暗角能同时保住吗？' },
  { id: 'old-town', cn: '古镇巷弄', cat: '建筑', ev: 9, dist: 25, speed: 0.8,
    prompt: 'a narrow ancient Chinese water-town alley at dusk, wet flagstones reflecting warm lantern light, whitewashed walls and dark tiled eaves, a lone cyclist turning a corner',
    note: '框架构图：让门洞、拱门替你画一个画框。' },

  /* ---------------- 纪实 ---------------- */
  { id: 'street-doc', cn: '街头纪实', cat: '纪实', ev: 11, dist: 8, speed: 1.4,
    prompt: 'a decisive-moment street photograph, a man stepping over a puddle mid-stride, his reflection perfect in the still water, layered pedestrians and signage behind him, complex urban choreography',
    note: '布列松的决定性瞬间。35mm，快，别让人发现你。' },
  { id: 'market', cn: '集市人文', cat: '纪实', ev: 9, dist: 5, speed: 1,
    prompt: 'a bustling morning market in an old Asian city, a vendor weighing vegetables on a brass scale under a bare bulb, steam and smoke, hands and produce filling the frame with life',
    note: '光线杂乱时，靠近 + 大光圈是划出重点的办法。' },
  { id: 'train', cn: '铁道', cat: '纪实', ev: 10, dist: 40, speed: 30,
    prompt: 'a freight train thundering through a rural valley, exhaust and dust swirling, long lens compressing the carriages into a solid wall of steel, distant hills layered behind',
    note: '30 m/s 的主体。除了追随，你几乎没有别的选择。' },

  /* ---------------- 运动 ---------------- */
  { id: 'sport-cycle', cn: '公路自行车', cat: '运动', ev: 13, dist: 12, speed: 9,
    prompt: 'a road cyclist sprinting out of the saddle, muscle definition and tendons straining, water bottle rattling, sweat spray, motion implied by the body position',
    note: '摇拍的教科书场景：机身随人转，人被凝固，背景拉成线。' },
  { id: 'sport-field', cn: '田径瞬间', cat: '运动', ev: 14, dist: 25, speed: 8,
    prompt: 'a long jumper at the exact instant of takeoff, sand exploding behind her heel, body fully extended, stadium crowd blurred into colour behind',
    note: '预判比快门更重要。1/2000 凝固沙粒。' },

  /* ---------------- 自然与微距 ---------------- */
  { id: 'wildlife', cn: '野生动物', cat: '自然', ev: 13, dist: 20, speed: 6,
    prompt: 'a red fox pausing mid-step in a frost-covered meadow, ears pricked, breath steaming in the cold air, fur detail sharp, background melting into golden bokeh',
    note: '长焦 + 连拍。600mm 的压缩会把背景揉成一团奶油。' },
  { id: 'bird-flight', cn: '飞鸟', cat: '自然', ev: 13, dist: 15, speed: 12,
    prompt: 'a kingfisher diving toward the water, wings swept back in a streamline, droplet trail behind it, water surface moments before impact',
    note: '1/4000 才抓得住翅膀。这是快门速度最直观的演示。' },
  { id: 'flower-macro', cn: '花卉微距', cat: '微距', ev: 11, dist: 0.3, speed: 0.02,
    prompt: 'macro photograph of a dew-covered spiderweb strung between lavender stems, each droplet a tiny refracting lens, background dissolved into pure soft colour',
    note: '微距下景深只有几毫米。f/16 都不一定够，尝试景深合成。' },
  { id: 'insect-macro', cn: '昆虫微距', cat: '微距', ev: 11, dist: 0.2, speed: 0.15,
    prompt: 'an extreme close-up of a jumping spider on a leaf edge, every hair and each of its eight eyes in razor detail, iridescent chelicerae catching the light',
    note: '1:1 放大倍率。光圈越小景深越大，但衍射也会来。' },

  /* ---------------- 静物与生活 ---------------- */
  { id: 'still-life', cn: '静物', cat: '静物', ev: 8, dist: 0.8, speed: 0,
    prompt: 'still life of a half-peeled orange, a chipped ceramic bowl and a tarnished silver spoon on dark linen, single soft window light from the left, deep shadow falling to the right',
    note: '静物是练光的地方——你有全部的时间去调整。' },
  { id: 'food', cn: '美食', cat: '静物', ev: 9, dist: 0.7, speed: 0,
    prompt: 'overhead food photograph of a steaming bowl of hand-pulled noodles, scattered spring onions and chili oil swirls, chopsticks lifting one strand, moody dark wood table',
    note: '侧逆光让蒸汽visible，45° 是食物的常规角度。' },
  { id: 'cafe-window', cn: '咖啡馆窗边', cat: '生活', ev: 8, dist: 1.5, speed: 0,
    prompt: 'a barista pouring latte art into a cup on a worn wooden counter, steam curling into a shaft of morning light from the window, dust motes and warm backlit haze',
    note: '窗光是免费的柔光箱。逆光 + 蒸汽 = 氛围。' },
  { id: 'car-night', cn: '车与夜', cat: '生活', ev: 6, dist: 8, speed: 0,
    prompt: 'a classic sports car parked under a sodium streetlamp on a wet road at night, paintwork reflecting the lights, faint mist, cinematic stillness',
    note: '低光静物。三脚架 + 长曝，或者咬牙上 ISO 6400。' }
];

/* ------------------------------------------------------------------ 摄影手法 */
window.TECHNIQUES = [
  { id: 'none', cn: '常规拍摄', cat: '常规', token: '', note: '' },
  { id: 'panning', cn: '追随拍摄（摇拍）', cat: '运动', token: 'panning shot with the camera tracking the moving subject, the subject is pin sharp while the background is smeared into long horizontal motion blur streaks',
    note: '机身跟着主体转，主体清晰、背景拉线。这是「用模糊表达速度」最经典的手法。', force: { shutter: 1 / 30 } },
  { id: 'freeze', cn: '高速凝固', cat: '运动', token: 'high-speed capture freezing a split second of motion, every droplet and fibre suspended perfectly still',
    note: '快门足够快时，瞬间被冻结成标本。', force: { shutter: 1 / 2000 } },
  { id: 'drag', cn: '慢门拖影', cat: '运动', token: 'slow shutter drag leaving a soft ghosting smear trailing the moving subject, ambient light blending with the subject',
    note: '快门介于「凝固」与「消失」之间——留一点痕迹，速度感最强。', force: { shutter: 1 / 8 } },
  { id: 'longexp', cn: '长时间曝光', cat: '夜景', token: 'long exposure photograph, time compressed into a single frame, water smoothed to glass, clouds streaked into ribbons',
    note: '把时间当作画笔。三脚架是必需品。', force: { shutter: 15 } },
  { id: 'lightpainting', cn: '光绘', cat: '夜景', token: 'light painting performed during a long bulb exposure, a moving hand-held light source drawing luminous lines of colour through the darkness',
    note: '黑暗是画布，手电是笔。', force: { shutter: 30 } },
  { id: 'startrail', cn: '星轨', cat: '夜景', token: 'star trail photograph from a long exposure, the stars over hours drawn into concentric arcs around the celestial pole',
    note: '地球自转的显影。', force: { shutter: 600 } },
  { id: 'zoom-burst', cn: '变焦拉爆', cat: '特效', token: 'zoom burst effect, the lens zoomed during the exposure so light streaks radially outward from the centre',
    note: '曝光中途变焦，光往外射。', force: { shutter: 1 / 4 } },
  { id: 'icm', cn: '有意晃动（ICM）', cat: '特效', token: 'intentional camera movement, the camera deliberately swept during exposure painting the scene into abstract impressionistic streaks of colour',
    note: '故意晃动，把风景拍成印象派油画。', force: { shutter: 1 / 4 } },
  { id: 'multiple-exp', cn: '多重曝光', cat: '特效', token: 'multiple exposure, two or more frames superimposed so different elements ghost through one another',
    note: '两段时间叠在同一张底片上。', force: {} },
  { id: 'strobe-multi', cn: '频闪定格', cat: '特效', token: 'stroboscopic flash firing several times during one exposure, a single moving figure repeated in a sequence of frozen poses across the frame',
    note: '一次曝光里拍下运动的连续切片。', force: { shutter: 2 } },
  { id: 'focus-stack', cn: '景深合成', cat: '技术', token: 'focus stacked image combining multiple exposures, every part of the scene from front to back impossibly sharp',
    note: '微距与风光的解药：多张不同焦点合成无限景深。', force: {} },
  { id: 'bokeh-pan', cn: '散景墙', cat: '技术', token: 'subject placed against a deep wall of bokeh, dozens of out-of-focus highlights forming a shimmering luminous curtain behind them',
    note: '用大光圈把背景的光点变成一张发光的幕布。', force: { aperture: 1.4 } },
  { id: 'silhouette', cn: '剪影', cat: '光线', token: 'pure silhouette, the subject rendered as a solid dark shape against a bright glowing background, no detail visible in the form',
    note: '关掉一切对主体的补光，只让它成为形状。' },
  { id: 'backlight', cn: '逆光', cat: '光线', token: 'strong backlight, the sun behind the subject rimming its edges in brilliant light, haze and flare washing across the frame',
    note: '逆光是风险也是机会：要么大光晕，要么曝光补偿。', force: {} },
  { id: 'rimlight', cn: '轮廓光', cat: '光线', token: 'dramatic rim lighting tracing a thin band of light around the subject, separating it from a dark background' },
  { id: 'golden-hour', cn: '黄金时刻', cat: '光线', token: 'photographed during golden hour, the low sun raking across the scene in warm amber light, long soft shadows stretching toward the camera' },
  { id: 'blue-hour', cn: '蓝调时刻', cat: '光线', token: 'photographed during blue hour just after sunset, sky a deep luminous cobalt, artificial lights beginning to glow against the cold ambient' },
  { id: 'overcast', cn: '阴天柔光', cat: '光线', token: 'overcast diffused daylight, an enormous soft light source producing gentle shadowless illumination and saturated muted colour' },
  { id: 'high-key', cn: '高调', cat: '光线', token: 'high key lighting, brightly lit white-on-white scene with almost no shadows, airy delicate luminous mood' },
  { id: 'low-key', cn: '低调', cat: '光线', token: 'low key lighting, the subject emerging from deep darkness with a single shaped pool of light, mostly shadow with sculpted highlights' },
  { id: 'rembrandt', cn: '伦勃朗光', cat: '光位', token: 'Rembrandt lighting, a single light at 45 degrees above and to the side, forming a small inverted triangle of light on the shadowed cheek' },
  { id: 'butterfly', cn: '蝴蝶光', cat: '光位', token: 'butterfly lighting, the key light directly above and in front of the face casting a symmetrical butterfly-shaped shadow beneath the nose' },
  { id: 'split', cn: '阴阳脸', cat: '光位', token: 'split lighting, the face divided exactly in half by light and shadow, dramatic and graphic, the lit eye bright against the dark side' },
  { id: 'three-point', cn: '三点布光', cat: '光位', token: 'classic three point lighting, key light, fill light and back light modelling the subject with full dimensional control' },
  { id: 'hard-light', cn: '硬光', cat: '光位', token: 'hard bare-bulb light source, razor-sharp shadow edges, high contrast, dramatic specular highlights' },
  { id: 'soft-light', cn: '柔光', cat: '光位', token: 'large softbox light source producing a gradual soft shadow transition and smooth wrapping illumination' },
  { id: 'reflector', cn: '反光板补光', cat: '光位', token: 'a white reflector bouncing fill light into the shadow side, lifting the shadow detail while keeping the direction of light' }
];

/* ------------------------------------------------------------------ 构图 */
window.COMPOSITIONS = [
  { id: 'none', cn: '自由构图', token: '' },
  { id: 'thirds', cn: '三分法', token: 'composed with the subject placed on a rule-of-thirds intersection, off-centre and balanced' },
  { id: 'centre', cn: '中心对称', token: 'symmetrical central composition, the subject dead centre with mirrored balance around it' },
  { id: 'leading', cn: '引导线', token: 'strong leading lines drawing the eye from the foreground into the depth of the frame toward the subject' },
  { id: 'frame', cn: '框架构图', token: 'the subject framed within a natural frame such as a doorway, arch or window, adding depth and enclosure' },
  { id: 'negative', cn: '大量留白', token: 'generous negative space around the subject, minimal and quiet, the emptiness carrying as much weight as the subject' },
  { id: 'diagonal', cn: '对角线', token: 'diagonal composition running corner to corner, dynamic and energetic' },
  { id: 'low-angle', cn: '低角度仰拍', token: 'shot from a very low angle looking up, making the subject tower and dominate the frame' },
  { id: 'high-angle', cn: '高角度俯拍', token: 'shot from a high angle looking down, flattening the scene into graphic shapes' },
  { id: 'dutch', cn: '荷兰角倾斜', token: 'dutch tilt, the horizon deliberately rotated, creating unease and dynamism' },
  { id: 'fill-frame', cn: '充满画面', token: 'the subject filling the entire frame edge to edge, cropping tight and intimate, no background at all' },
  { id: 'layered', cn: '前景中景远景', token: 'layered composition with a distinct foreground, midground and background creating depth and narrative' }
];
